if(NOT DEFINED CLI OR NOT DEFINED CASE_DIR)
  message(FATAL_ERROR "missing test configuration")
endif()
file(MAKE_DIRECTORY "${CASE_DIR}")
file(WRITE "${CASE_DIR}/valid.json" "{\"schema_version\":2,\"payload\":\"abc\",\"integrity\":{\"algorithm\":\"sha256\",\"digest\":\"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad\"}}")
execute_process(COMMAND "${CLI}" verify-report-v2 "${CASE_DIR}/valid.json" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT output MATCHES "integrity_verified.*true" OR NOT error STREQUAL "")
  message(FATAL_ERROR "valid v2 report rejected: ${result}: ${output} ${error}")
endif()
file(WRITE "${CASE_DIR}/tampered.json" "{\"schema_version\":2,\"payload\":\"abd\",\"integrity\":{\"algorithm\":\"sha256\",\"digest\":\"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad\"}}")
execute_process(COMMAND "${CLI}" verify-report-v2 "${CASE_DIR}/tampered.json" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 2 OR NOT output STREQUAL "" OR NOT error MATCHES "integrity verification failed")
  message(FATAL_ERROR "tampered v2 report accepted: ${result}: ${output} ${error}")
endif()
