if(NOT DEFINED CLI OR NOT DEFINED SPEC OR NOT DEFINED ADAPTER OR NOT DEFINED CASE_DIR)
  message(FATAL_ERROR "missing test configuration")
endif()
file(MAKE_DIRECTORY "${CASE_DIR}")
file(READ "${SPEC}" model_json)
file(SHA256 "${ADAPTER}" adapter_digest)
set(payload "{\"model\":${model_json},\"generator\":{\"strategy\":\"seeded-dfs-v1\",\"termination_status\":\"dead_end\"},\"flow\":{\"flow_id\":\"produce\",\"transition_ids\":[\"produce\",\"consume\"]},\"adapter\":{\"path\":\"${ADAPTER}\",\"sha256\":\"${adapter_digest}\",\"arguments\":[],\"working_directory\":\"${CASE_DIR}\"},\"runtime\":{\"step_timeout_ms\":2000,\"total_timeout_ms\":30000,\"output_limit_bytes\":16777216,\"environment\":[\"PATH=/usr/bin:/bin\",\"LC_ALL=C\"]},\"result\":{\"status\":\"timeout\",\"flow_id\":\"produce\",\"steps\":[]}}")
file(WRITE "${CASE_DIR}/payload.json" "${payload}")
execute_process(COMMAND "${CLI}" wrap-report-v2 "${CASE_DIR}/payload.json"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT error STREQUAL "")
  message(FATAL_ERROR "v2 wrapping failed: ${result}: ${error}")
endif()
file(WRITE "${CASE_DIR}/envelope.json" "${output}")
execute_process(COMMAND "${CLI}" verify-report-v2 "${CASE_DIR}/envelope.json"
  RESULT_VARIABLE verify_result OUTPUT_VARIABLE verify_output ERROR_VARIABLE verify_error)
if(NOT verify_result EQUAL 0 OR NOT verify_output MATCHES "payload_valid.*true")
  message(FATAL_ERROR "wrapped payload rejected: ${verify_result}: ${verify_output} ${verify_error}")
endif()
file(WRITE "${CASE_DIR}/invalid.json" "not-json")
execute_process(COMMAND "${CLI}" wrap-report-v2 "${CASE_DIR}/invalid.json"
  RESULT_VARIABLE invalid_result OUTPUT_VARIABLE invalid_output ERROR_VARIABLE invalid_error)
if(NOT invalid_result EQUAL 2 OR NOT invalid_output STREQUAL "" OR NOT invalid_error MATCHES "invalid RFC8259 JSON")
  message(FATAL_ERROR "invalid payload accepted: ${invalid_result}: ${invalid_output} ${invalid_error}")
endif()
