if(NOT DEFINED CLI OR NOT DEFINED SPEC OR NOT DEFINED ADAPTER OR NOT DEFINED CASE_DIR)
  message(FATAL_ERROR "missing test configuration")
endif()
file(MAKE_DIRECTORY "${CASE_DIR}")
file(WRITE "${CASE_DIR}/integrity-valid-payload.json" "123")
execute_process(COMMAND "${CLI}" wrap-report-v2 "${CASE_DIR}/integrity-valid-payload.json" OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${CASE_DIR}/valid.json" "${output}")
execute_process(COMMAND "${CLI}" verify-report-v2 "${CASE_DIR}/valid.json" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 2 OR NOT output STREQUAL "" OR NOT error MATCHES "invalid report v2 payload")
  message(FATAL_ERROR "schema-invalid v2 report accepted: ${result}: ${output} ${error}")
endif()
file(WRITE "${CASE_DIR}/tampered.json" "{\"schema_version\":2,\"payload\":\"124\",\"integrity\":{\"algorithm\":\"sha256\",\"digest\":\"a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3\"}}")
execute_process(COMMAND "${CLI}" verify-report-v2 "${CASE_DIR}/tampered.json" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 2 OR NOT output STREQUAL "" OR NOT error MATCHES "integrity verification failed")
  message(FATAL_ERROR "tampered v2 report accepted: ${result}: ${output} ${error}")
endif()
file(READ "${CASE_DIR}/valid.json" valid)
foreach(name IN ITEMS algorithm extra digest duplicate version trailing)
  if(name STREQUAL "algorithm")
    string(REPLACE "sha256" "md5" body "${valid}")
  elseif(name STREQUAL "extra")
    string(REPLACE "\"payload\":" "\"extra\":1,\"payload\":" body "${valid}")
  elseif(name STREQUAL "digest")
    string(REPLACE "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3" "deadbeef" body "${valid}")
  elseif(name STREQUAL "duplicate")
    string(REPLACE "\"payload\":" "\"payload\":\"123\",\"payload\":" body "${valid}")
  elseif(name STREQUAL "version")
    string(REPLACE "\"schema_version\":2" "\"schema_version\":3" body "${valid}")
  else()
    set(body "${valid} trailing")
  endif()
  file(WRITE "${CASE_DIR}/${name}.json" "${body}")
  execute_process(COMMAND "${CLI}" verify-report-v2 "${CASE_DIR}/${name}.json"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 2 OR NOT output STREQUAL "" OR NOT error MATCHES "integrity verification failed")
    message(FATAL_ERROR "${name} envelope accepted: ${result}: ${output} ${error}")
  endif()
endforeach()
file(WRITE "${CASE_DIR}/non-json.json" "{\"schema_version\":2,\"payload\":\"abc\",\"integrity\":{\"algorithm\":\"sha256\",\"digest\":\"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad\"}}")
execute_process(COMMAND "${CLI}" verify-report-v2 "${CASE_DIR}/non-json.json" RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 2 OR NOT output STREQUAL "")
  message(FATAL_ERROR "non-JSON payload accepted")
endif()
file(READ "${SPEC}" model_json)
file(SHA256 "${ADAPTER}" adapter_digest)
set(payload "{\"model\":${model_json},\"generator\":{\"strategy\":\"seeded-dfs-v1\",\"termination_status\":\"dead_end\"},\"flow\":{\"flow_id\":\"produce\",\"transition_ids\":[\"produce\",\"consume\"]},\"adapter\":{\"path\":\"${ADAPTER}\",\"sha256\":\"${adapter_digest}\",\"arguments\":[],\"working_directory\":\"${CASE_DIR}\"},\"runtime\":{\"step_timeout_ms\":2000,\"total_timeout_ms\":30000,\"output_limit_bytes\":16777216,\"environment\":[\"PATH=/usr/bin:/bin\",\"LC_ALL=C\"]},\"result\":{\"status\":\"timeout\",\"flow_id\":\"produce\",\"steps\":[]}}")
file(WRITE "${CASE_DIR}/report-payload.json" "${payload}")
execute_process(COMMAND "${CLI}" wrap-report-v2 "${CASE_DIR}/report-payload.json" OUTPUT_VARIABLE envelope)
file(WRITE "${CASE_DIR}/report-envelope.json" "${envelope}")
execute_process(COMMAND "${CLI}" verify-report-v2 "${CASE_DIR}/report-envelope.json" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT output STREQUAL "{\"valid\":true,\"integrity_verified\":true,\"payload_valid\":true,\"schema_version\":2}\n" OR NOT error STREQUAL "")
  message(FATAL_ERROR "valid v2 report rejected: ${result}: ${output} ${error}")
endif()
