if(NOT DEFINED BUILD_DIR OR NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "missing coverage gate configuration")
endif()
find_program(GCOV gcov REQUIRED)
file(GLOB_RECURSE data_files "${BUILD_DIR}/*.gcda")
if(NOT data_files)
  message(FATAL_ERROR "no coverage data found; build with WISE_COMBINE_ENABLE_COVERAGE and run CTest first")
endif()
set(covered 0)
set(total 0)
foreach(data IN LISTS data_files)
  execute_process(COMMAND ${GCOV} -n ${data} OUTPUT_VARIABLE report ERROR_VARIABLE error RESULT_VARIABLE status)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "gcov failed: ${error}")
  endif()
  string(REGEX MATCHALL "File '[^']*'\nLines executed:[0-9.]+% of [0-9]+" records "${report}")
  foreach(record IN LISTS records)
    if(record MATCHES "File '${SOURCE_DIR}/src/[^']*'\nLines executed:([0-9.]+)% of ([0-9]+)")
      set(percent "${CMAKE_MATCH_1}")
      set(lines "${CMAKE_MATCH_2}")
      string(REGEX REPLACE "\\..*" "" integer_percent "${percent}")
      math(EXPR total "${total} + ${lines}")
      math(EXPR covered "${covered} + (${integer_percent} * ${lines})")
    endif()
  endforeach()
endforeach()
if(total EQUAL 0)
  message(FATAL_ERROR "no project source coverage records found")
endif()
math(EXPR percent "${covered} / ${total}")
message(STATUS "project source coverage: ${percent}% (${total} executable lines)")
if(percent LESS 80)
  message(FATAL_ERROR "coverage below required 80%")
endif()
