if(NOT DEFINED CLI OR NOT DEFINED CASE_DIR)
  message(FATAL_ERROR "missing test configuration")
endif()
file(MAKE_DIRECTORY "${CASE_DIR}")
set(valid [=[{"generation_status":"dead_end","case_count":3,"passed":2,"failed":1,"seed":9,"wall_time_ns":1,"cpu_time_ns":1,"peak_rss_bytes":1}]=])
file(WRITE "${CASE_DIR}/summary.json" "${valid}")
execute_process(COMMAND "${CLI}" verify-report "${CASE_DIR}/summary.json"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result STREQUAL "0" OR NOT output MATCHES "\"valid\":true")
  message(FATAL_ERROR "valid summary rejected: ${result}: ${output} ${error}")
endif()
foreach(replacement IN ITEMS "\"failed\":2" "\"failed\":-1" "\"failed\":1.0" "\"failed\":\"1\"" "\"failed\":9223372036854775807")
  string(REPLACE "\"failed\":1" "${replacement}" invalid "${valid}")
  file(WRITE "${CASE_DIR}/invalid.json" "${invalid}")
  execute_process(COMMAND "${CLI}" verify-report "${CASE_DIR}/invalid.json"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result STREQUAL "2" OR NOT output STREQUAL "")
    message(FATAL_ERROR "invalid summary accepted: ${replacement}: ${result}: ${output} ${error}")
  endif()
endforeach()
