#include "spec/spec.hpp"

#include <algorithm>
#include <charconv>
#include <cctype>
#include <cmath>
#include <iomanip>
#include <map>
#include <set>
#include <sstream>
#include <string_view>
#include <variant>

namespace wise::spec {
namespace {
struct Value { using Object = std::map<std::string, Value>; using Array = std::vector<Value>; std::variant<std::nullptr_t, bool, std::int64_t, double, std::string, Object, Array> data; };

class Parser {
 public:
  explicit Parser(std::string_view input) : input_(input) {}
  Value parse() { ws(); Value result = value(); ws(); if (pos_ != input_.size()) fail(""); return result; }
 private:
  std::string_view input_; std::size_t pos_{0};
  [[noreturn]] void fail(const std::string& pointer) const { throw SpecError({{pointer, "invalid RFC8259 JSON"}}); }
  void ws() { while (pos_ < input_.size() && std::isspace(static_cast<unsigned char>(input_[pos_]))) ++pos_; }
  bool take(std::string_view token) { if (input_.substr(pos_, token.size()) != token) return false; pos_ += token.size(); return true; }
  Value value() { ws(); if (pos_ >= input_.size()) fail(""); switch (input_[pos_]) { case '{': return object(); case '[': return array(); case '"': return Value{string()}; case 't': if (take("true")) return Value{true}; break; case 'f': if (take("false")) return Value{false}; break; case 'n': if (take("null")) return Value{nullptr}; break; default: if (input_[pos_] == '-' || std::isdigit(static_cast<unsigned char>(input_[pos_]))) return number(); } fail(""); }
  static int hex(char c) { if (c >= '0' && c <= '9') return c - '0'; if (c >= 'a' && c <= 'f') return c - 'a' + 10; if (c >= 'A' && c <= 'F') return c - 'A' + 10; return -1; }
  std::string string() { if (pos_ >= input_.size() || input_[pos_++] != '"') fail(""); std::string out; while (pos_ < input_.size()) { const unsigned char c = static_cast<unsigned char>(input_[pos_++]); if (c == '"') return out; if (c < 0x20U) fail(""); if (c != '\\') { out.push_back(static_cast<char>(c)); continue; } if (pos_ >= input_.size()) fail(""); const char e = input_[pos_++]; const std::string esc = "\"\\/bfnrt"; const auto index = esc.find(e); if (index != std::string::npos) { const char values[] = {'"', '\\', '/', '\b', '\f', '\n', '\r', '\t'}; out.push_back(values[index]); continue; } if (e != 'u' || pos_ + 4 > input_.size()) fail(""); unsigned code = 0; for (int i = 0; i < 4; ++i) { const int d = hex(input_[pos_++]); if (d < 0) fail(""); code = code * 16U + static_cast<unsigned>(d); } if (code >= 0xD800U && code <= 0xDBFFU) { if (pos_ + 6 > input_.size() || input_[pos_] != '\\' || input_[pos_ + 1] != 'u') fail(""); pos_ += 2; unsigned low = 0; for (int i = 0; i < 4; ++i) { const int d = hex(input_[pos_++]); if (d < 0) fail(""); low = low * 16U + static_cast<unsigned>(d); } if (low < 0xDC00U || low > 0xDFFFU) fail(""); code = 0x10000U + ((code - 0xD800U) << 10U) + low - 0xDC00U; } else if (code >= 0xDC00U && code <= 0xDFFFU) fail(""); if (code <= 0x7FU) out.push_back(static_cast<char>(code)); else if (code <= 0x7FFU) { out.push_back(static_cast<char>(0xC0U | (code >> 6U))); out.push_back(static_cast<char>(0x80U | (code & 0x3FU))); } else if (code <= 0xFFFFU) { out.push_back(static_cast<char>(0xE0U | (code >> 12U))); out.push_back(static_cast<char>(0x80U | ((code >> 6U) & 0x3FU))); out.push_back(static_cast<char>(0x80U | (code & 0x3FU))); } else { out.push_back(static_cast<char>(0xF0U | (code >> 18U))); out.push_back(static_cast<char>(0x80U | ((code >> 12U) & 0x3FU))); out.push_back(static_cast<char>(0x80U | ((code >> 6U) & 0x3FU))); out.push_back(static_cast<char>(0x80U | (code & 0x3FU))); } } fail(""); }
  Value number() { const auto begin = pos_; if (input_[pos_] == '-') ++pos_; if (pos_ >= input_.size()) fail(""); if (input_[pos_] == '0') ++pos_; else { if (input_[pos_] < '1' || input_[pos_] > '9') fail(""); while (pos_ < input_.size() && std::isdigit(static_cast<unsigned char>(input_[pos_]))) ++pos_; } bool real = false; if (pos_ < input_.size() && input_[pos_] == '.') { real = true; ++pos_; const auto start = pos_; while (pos_ < input_.size() && std::isdigit(static_cast<unsigned char>(input_[pos_]))) ++pos_; if (start == pos_) fail(""); } if (pos_ < input_.size() && (input_[pos_] == 'e' || input_[pos_] == 'E')) { real = true; ++pos_; if (pos_ < input_.size() && (input_[pos_] == '+' || input_[pos_] == '-')) ++pos_; const auto start = pos_; while (pos_ < input_.size() && std::isdigit(static_cast<unsigned char>(input_[pos_]))) ++pos_; if (start == pos_) fail(""); } const std::string text(input_.substr(begin, pos_ - begin)); try { if (real) { const double result = std::stod(text); if (!std::isfinite(result)) fail(""); return Value{result}; } return Value{std::stoll(text)}; } catch (...) { fail(""); } }
  Value object() { ++pos_; Value::Object out; ws(); if (pos_ < input_.size() && input_[pos_] == '}') { ++pos_; return Value{out}; } while (true) { ws(); if (pos_ >= input_.size() || input_[pos_] != '"') fail(""); const std::string key = string(); ws(); if (pos_ >= input_.size() || input_[pos_++] != ':') fail(""); if (!out.emplace(key, value()).second) fail(""); ws(); if (pos_ >= input_.size()) fail(""); if (input_[pos_] == '}') { ++pos_; return Value{out}; } if (input_[pos_++] != ',') fail(""); } }
  Value array() { ++pos_; Value::Array out; ws(); if (pos_ < input_.size() && input_[pos_] == ']') { ++pos_; return Value{out}; } while (true) { out.push_back(value()); ws(); if (pos_ >= input_.size()) fail(""); if (input_[pos_] == ']') { ++pos_; return Value{out}; } if (input_[pos_++] != ',') fail(""); } }
};

using Object = Value::Object;
[[noreturn]] void invalid(const std::string& pointer, const std::string& message) { throw SpecError({{pointer, message}}); }
const Object& obj(const Value& v, const std::string& p) { if (const auto* x = std::get_if<Object>(&v.data)) return *x; invalid(p, "expected object"); }
const Value::Array& arr(const Value& v, const std::string& p) { if (const auto* x = std::get_if<Value::Array>(&v.data)) return *x; invalid(p, "expected array"); }
const Value& required(const Object& o, const std::string& key, const std::string& p) { const auto it = o.find(key); if (it == o.end()) invalid(p + "/" + key, "missing required field"); return it->second; }
std::string text(const Object& o, const std::string& key, const std::string& p) { const auto& v = required(o, key, p); if (const auto* x = std::get_if<std::string>(&v.data); x != nullptr && !x->empty()) return *x; invalid(p + "/" + key, "expected non-empty string"); }
void strict_keys(const Object& o, std::initializer_list<const char*> allowed, const std::string& p) { for (const auto& [key, value] : o) { static_cast<void>(value); if (std::find(allowed.begin(), allowed.end(), key) == allowed.end()) invalid(p + "/" + key, "unknown field"); } }
std::string quote(const std::string& s) { std::ostringstream out; out << '"'; for (const unsigned char c : s) { if (c == '"' || c == '\\') out << '\\' << c; else if (c == '\n') out << "\\n"; else if (c == '\r') out << "\\r"; else if (c == '\t') out << "\\t"; else if (c < 0x20U) out << "\\u" << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(c) << std::dec; else out << static_cast<char>(c); } return out << '"', out.str(); }
std::string canonical(const Value& v) { if (std::holds_alternative<std::nullptr_t>(v.data)) return "null"; if (const auto* x = std::get_if<bool>(&v.data)) return *x ? "true" : "false"; if (const auto* x = std::get_if<std::int64_t>(&v.data)) return std::to_string(*x); if (const auto* x = std::get_if<double>(&v.data)) { char b[64]; const auto r = std::to_chars(b, b + sizeof(b), *x); return std::string(b, r.ptr); } if (const auto* x = std::get_if<std::string>(&v.data)) return quote(*x); if (const auto* x = std::get_if<Value::Array>(&v.data)) { std::string out = "["; for (std::size_t i = 0; i < x->size(); ++i) { if (i) out += ','; out += canonical((*x)[i]); } return out + ']'; } std::string out = "{"; bool first = true; for (const auto& [key, child] : std::get<Object>(v.data)) { if (!first) out += ','; first = false; out += quote(key) + ':' + canonical(child); } return out + '}'; }
}

SpecError::SpecError(std::vector<Diagnostic> d) : std::runtime_error(d.empty() ? "spec error" : d.front().pointer + ": " + d.front().message), diagnostics_(std::move(d)) {}

Document parse(const std::string& json) {
  const Object& top = obj(Parser(json).parse(), ""); strict_keys(top, {"version", "states", "initial_state", "transitions", "functions", "relations", "limits", "seed"}, "");
  const auto* version = std::get_if<std::int64_t>(&required(top, "version", "").data); if (version == nullptr || *version != 1) invalid("/version", "unsupported version; expected integer 1");
  Document d; const auto& states = arr(required(top, "states", ""), "/states"); for (std::size_t i = 0; i < states.size(); ++i) { const auto& x = obj(states[i], "/states/" + std::to_string(i)); strict_keys(x, {"id"}, "/states/" + std::to_string(i)); d.model.add_state({text(x, "id", "/states/" + std::to_string(i))}); } d.model.set_initial_state(text(top, "initial_state", ""));
  const auto& functions = arr(required(top, "functions", ""), "/functions"); for (std::size_t i = 0; i < functions.size(); ++i) { const auto& x = obj(functions[i], ""); strict_keys(x, {"id", "params", "returns"}, ""); model::Function f; f.id = text(x, "id", ""); for (const auto& y : arr(required(x, "params", ""), "")) { const auto& p = obj(y, ""); strict_keys(p, {"name", "type"}, ""); f.parameters.push_back({text(p, "name", ""), text(p, "type", "")}); } for (const auto& y : arr(required(x, "returns", ""), "")) { const auto& p = obj(y, ""); strict_keys(p, {"name", "type"}, ""); f.returns.push_back({text(p, "name", ""), text(p, "type", "")}); } d.model.add_function(std::move(f)); }
  const auto& transitions = arr(required(top, "transitions", ""), "/transitions"); for (const auto& y : transitions) { const auto& x = obj(y, ""); strict_keys(x, {"id", "from", "to", "function", "args", "expect"}, ""); model::Transition t{text(x, "id", ""), text(x, "from", ""), text(x, "to", ""), text(x, "function", "")}; if (const auto it = x.find("args"); it != x.end()) { for (const auto& [name, value] : obj(it->second, "")) { model::Scalar s; if (std::holds_alternative<std::nullptr_t>(value.data)) s.kind = model::Scalar::Kind::null_value; else if (const auto* b = std::get_if<bool>(&value.data)) { s.kind = model::Scalar::Kind::boolean; s.boolean_value = *b; } else if (const auto* n = std::get_if<std::int64_t>(&value.data)) { s.kind = model::Scalar::Kind::integer; s.integer_value = *n; } else if (const auto* n = std::get_if<double>(&value.data)) { s.kind = model::Scalar::Kind::number; s.number_value = *n; } else if (const auto* svalue = std::get_if<std::string>(&value.data)) { s.kind = model::Scalar::Kind::string; s.string_value = *svalue; } else invalid("/transitions/args", "expected scalar"); t.args.emplace(name, s); } } if (const auto it = x.find("expect"); it != x.end()) { const auto& e = obj(it->second, ""); strict_keys(e, {"state"}, ""); t.expect_present = true; t.expect = text(e, "state", ""); } d.model.add_transition(std::move(t)); }
  for (const auto& y : arr(required(top, "relations", ""), "/relations")) { const auto& x = obj(y, "/relations"); const auto kind = text(x, "kind", "/relations"); if (kind == "argument") { strict_keys(x, {"kind", "producer", "consumer"}, "/relations"); const auto& p = obj(required(x, "producer", "/relations"), "/relations/producer"); const auto& c = obj(required(x, "consumer", "/relations"), "/relations/consumer"); strict_keys(p, {"transition", "output"}, "/relations/producer"); strict_keys(c, {"transition", "arg"}, "/relations/consumer"); d.model.add_argument_relation({text(p, "transition", ""), text(p, "output", ""), text(c, "transition", ""), text(c, "arg", "")}); } else if (kind == "before") { strict_keys(x, {"kind", "before", "after"}, "/relations"); d.model.add_ordering_relation({text(x, "before", "/relations"), text(x, "after", "/relations")}); } else invalid("/relations/kind", "unsupported relation kind"); }
  const auto& limits = obj(required(top, "limits", ""), "/limits"); strict_keys(limits, {"max_cases", "max_steps", "max_subprocesses"}, "/limits"); auto positive = [&](const char* key) { const auto* n = std::get_if<std::int64_t>(&required(limits, key, "/limits").data); if (n == nullptr || *n <= 0) invalid(std::string("/limits/") + key, "expected positive integer"); return static_cast<std::size_t>(*n); }; d.model.set_limits({positive("max_cases"), positive("max_steps"), positive("max_subprocesses")}); const auto* seed = std::get_if<std::int64_t>(&required(top, "seed", "").data); if (seed == nullptr || *seed < 0) invalid("/seed", "expected unsigned integer"); d.seed = static_cast<std::uint64_t>(*seed);
  try { d.model.validate(); } catch (const model::ModelError& e) { throw SpecError({{"", std::string("semantic validation failed: ") + e.what()}}); } d.canonical_json = canonical(Parser(json).parse()); return d;
}
std::string normalize(const std::string& json) { return parse(json).canonical_json; }
}
